  openapi_server:
    type: openapi
    kind: server
    options:
      specs:
        petstore:
          catalog:
            my_catalog:
              subject: petstore
              version: latest
    exit: openapi_client
