  asyncapi_client:
    type: asyncapi
    kind: client
    options:
      specs:
        my-kafka-api-spec:
          server: kafka://localhost:9092
          catalog:
            my_catalog:
              subject: petstore
              version: latest
