  asyncapi_proxy:
    type: asyncapi
    kind: proxy
    options:
      specs:
        my-mqtt-api-spec:
          servers:
            - mqtt://localhost:1883
          catalog:
            my_catalog:
              subject: mqtt-streetlights
              version: latest
        my-kafka-api-spec:
          servers:
            - kafka://localhost:9092
          catalog:
            my_catalog:
              subject: kafka-streetlights
              version: latest
    routes:
      - when:
          - spec: my-mqtt-api-spec
            operation: sendEvents
        exit: asyncapi_client
        with:
          spec: my-kafka-api-spec
          operation: toSensorData
      - when:
          - spec: my-mqtt-api-spec
            operation: receiveEvents
        exit: asyncapi_client
        with:
          spec: my-kafka-api-spec
          operation: onSensorData
