  mqtt_server:
    type: mqtt
    kind: server
    options:
      authorization:
        my_jwt_guard:
          credentials:
            connect:
              username: Bearer {credentials}
      versions:
        - v5
        - v3.1.1
    routes:
      - guarded:
          my_jwt_guard:
            - mqtt:stream
        when:
          - session:
              - client-id: "*"
          - publish:
              - topic: device/{id}/location
                params:
                  id: ${guarded['my_jwt_guard'].identity}
              - topic: device/{id}/temperature
                params:
                  id: ${guarded['my_jwt_guard'].identity}
          - subscribe:
              - topic: reply
    exit: mqtt_kafka_proxy
