name: Grammar check src

on:
  push:

jobs:
  grammarChecker:
    runs-on: ubuntu-latest
    container: jdkato/vale:v2.29.7
    steps:
      - uses: actions/checkout@v3
      - name: Grammar Checker
        run: vale src
      - name: Spell Check sidebar
        run: vale --ignore-syntax src/.vuepress/sidebar/en.ts
